#!/usr/bin/env pwsh
# ---------------------------------------------------------------------------
# Post-provision hook — writes azd outputs into the .env file for the lab
# ---------------------------------------------------------------------------
$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Post-Provision: Configuring lab environment"
Write-Host "============================================" -ForegroundColor Cyan

# Retrieve azd environment values
$projectEndpoint = azd env get-value AZURE_AI_PROJECT_ENDPOINT 2>$null
$modelName       = azd env get-value MODEL_DEPLOYMENT_NAME 2>$null
$modelName2      = azd env get-value MODEL_DEPLOYMENT_NAME_2 2>$null

if (-not $projectEndpoint) {
    Write-Host "WARNING: Could not retrieve AZURE_AI_PROJECT_ENDPOINT from azd." -ForegroundColor Yellow
    Write-Host "         You may need to set it manually in .env" -ForegroundColor Yellow
}

# Write .env file
$envPath = Join-Path $PSScriptRoot ".." ".env"
$envContent = @"
# Auto-generated by azd post-provision hook
# Project endpoint for Microsoft Foundry
PROJECT_ENDPOINT=$projectEndpoint

# Primary model deployment name
MODEL_DEPLOYMENT_NAME=$modelName
"@

if ($modelName2 -and $modelName2 -ne "") {
    $envContent += "`n`n# Second model for Lab 5 comparison`nMODEL_DEPLOYMENT_NAME_2=$modelName2"
}

Set-Content -Path $envPath -Value $envContent -Encoding UTF8

Write-Host ""
Write-Host "  .env file written to: $envPath" -ForegroundColor Green
Write-Host "  PROJECT_ENDPOINT:     $projectEndpoint" -ForegroundColor Green
Write-Host "  MODEL_DEPLOYMENT_NAME: $modelName" -ForegroundColor Green
if ($modelName2 -and $modelName2 -ne "") {
    Write-Host "  MODEL_DEPLOYMENT_NAME_2: $modelName2" -ForegroundColor Green
}
# Create and activate Python virtual environment
Write-Host ""
Write-Host "  Setting up Python virtual environment..." -ForegroundColor Cyan
$venvPath = Join-Path $PSScriptRoot ".." ".venv"
if (-not (Test-Path $venvPath)) {
    python -m venv $venvPath
    Write-Host "  Virtual environment created at: .venv" -ForegroundColor Green
} else {
    Write-Host "  Virtual environment already exists at: .venv"
}

$activateScript = Join-Path $venvPath "Scripts" "Activate.ps1"
if (Test-Path $activateScript) {
    & $activateScript
    Write-Host "  Virtual environment activated." -ForegroundColor Green
}

# Install Python dependencies
Write-Host ""
Write-Host "  Installing Python dependencies..." -ForegroundColor Cyan
$reqPath = Join-Path $PSScriptRoot ".." "requirements.txt"
if (Test-Path $reqPath) {
    pip install -r $reqPath --quiet 2>$null
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  Python dependencies installed." -ForegroundColor Green
    } else {
        Write-Host "  WARNING: pip install failed. Run manually: pip install -r requirements.txt" -ForegroundColor Yellow
    }
} else {
    Write-Host "  WARNING: requirements.txt not found." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Lab environment ready!"
Write-Host "  Run: python src/01_first_inference.py"
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""
