#!/bin/bash
# ---------------------------------------------------------------------------
# Post-provision hook — writes azd outputs into the .env file for the lab
# ---------------------------------------------------------------------------
set -e

echo ""
echo "============================================"
echo "  Post-Provision: Configuring lab environment"
echo "============================================"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# Retrieve azd environment values
PROJECT_ENDPOINT=$(azd env get-value AZURE_AI_PROJECT_ENDPOINT 2>/dev/null || echo "")
MODEL_NAME=$(azd env get-value MODEL_DEPLOYMENT_NAME 2>/dev/null || echo "gpt-5.4-mini")
MODEL_NAME_2=$(azd env get-value MODEL_DEPLOYMENT_NAME_2 2>/dev/null || echo "")
ACR_NAME=$(azd env get-value AZURE_CONTAINER_REGISTRY_NAME 2>/dev/null || echo "")

if [ -z "$PROJECT_ENDPOINT" ]; then
    echo "WARNING: Could not retrieve AZURE_AI_PROJECT_ENDPOINT from azd."
    echo "         You may need to set it manually in .env"
fi

# Write .env file
ENV_PATH="$ROOT_DIR/.env"
cat > "$ENV_PATH" <<EOF
# Auto-generated by azd post-provision hook
# Project endpoint for Microsoft Foundry
PROJECT_ENDPOINT=$PROJECT_ENDPOINT

# Primary model deployment name
MODEL_DEPLOYMENT_NAME=$MODEL_NAME
EOF

if [ -n "$MODEL_NAME_2" ]; then
    cat >> "$ENV_PATH" <<EOF

# Second model for Lab 5 comparison
MODEL_DEPLOYMENT_NAME_2=$MODEL_NAME_2
EOF
fi

if [ -n "$ACR_NAME" ]; then
    cat >> "$ENV_PATH" <<EOF

# Optional infrastructure output; not required for Lab 6 direct-code deployment
AZURE_CONTAINER_REGISTRY_NAME=$ACR_NAME
EOF
fi

echo ""
echo "  .env file written to: $ENV_PATH"
echo "  PROJECT_ENDPOINT:      $PROJECT_ENDPOINT"
echo "  MODEL_DEPLOYMENT_NAME: $MODEL_NAME"
if [ -n "$MODEL_NAME_2" ]; then
    echo "  MODEL_DEPLOYMENT_NAME_2: $MODEL_NAME_2"
fi
if [ -n "$ACR_NAME" ]; then
    echo "  AZURE_CONTAINER_REGISTRY_NAME: $ACR_NAME"
fi

# Create and activate Python virtual environment
echo ""
echo "  Setting up Python virtual environment..."
VENV_PATH="$ROOT_DIR/.venv"
if [ ! -d "$VENV_PATH" ]; then
    python3 -m venv "$VENV_PATH" || python -m venv "$VENV_PATH"
    echo "  Virtual environment created at: .venv"
else
    echo "  Virtual environment already exists at: .venv"
fi

if [ -f "$VENV_PATH/bin/activate" ]; then
    source "$VENV_PATH/bin/activate"
    echo "  Virtual environment activated."
fi

# Install Python dependencies
echo ""
echo "  Installing Python dependencies..."
REQ_PATH="$ROOT_DIR/requirements.txt"
if [ -f "$REQ_PATH" ]; then
    pip install -r "$REQ_PATH" --quiet 2>/dev/null && \
        echo "  Python dependencies installed." || \
        echo "  WARNING: pip install failed. Run manually: pip install -r requirements.txt"
else
    echo "  WARNING: requirements.txt not found."
fi

echo ""
echo "============================================"
echo "  Lab environment ready!"
echo "  Run: python src/01_first_inference.py"
echo "============================================"
echo ""
